//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelWebBanHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOA_DON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOA_DON()
        {
            this.CHITIET_HD = new HashSet<CHITIET_HD>();
        }
    
        public int MA_HD { get; set; }
        public Nullable<int> MA_KH { get; set; }
        public string MA_NV { get; set; }
        public System.DateTime NGAY_LAP { get; set; }
        public string TINH_GIAO_HANG { get; set; }
        public string DIA_CHI_GIAO_HANG { get; set; }
        public string GHI_CHU { get; set; }
        public Nullable<decimal> PHI_GIAO_HANG { get; set; }
        public Nullable<decimal> THANH_TIEN { get; set; }
        public Nullable<int> TRANG_THAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_HD> CHITIET_HD { get; set; }
        public virtual KHACH_HANG KHACH_HANG { get; set; }
        public virtual NHAN_VIEN NHAN_VIEN { get; set; }
    }
}
