//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelWebBanHang
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KHACH_HANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACH_HANG()
        {
            this.HOA_DON = new HashSet<HOA_DON>();
        }
    
        public int MA_KH { get; set; }
        public string MA_TV { get; set; }
        [Required(ErrorMessage = "Không Để Trống Tên")]
        public string TEN_KH { get; set; }
        public Nullable<bool> GIOI_TINH { get; set; }
        public Nullable<System.DateTime> NGAY_SINH { get; set; }
        public string TINH { get; set; }
        [Required(ErrorMessage = "Không Để Trống Địa Chỉ")]
        public string DIA_CHI { get; set; }
        [Required(ErrorMessage = "Không Để Trống Số Điện Thoại")]
        public string LIEN_HE { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOA_DON> HOA_DON { get; set; }
        public virtual THANH_VIEN THANH_VIEN { get; set; }
    }
}
