//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelWebBanHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class SAN_PHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SAN_PHAM()
        {
            this.CHITIET_HD = new HashSet<CHITIET_HD>();
        }
    
        public int MA_SP { get; set; }
        public string TEN_SP { get; set; }
        public string THONG_SO_KY_THUAT { get; set; }
        public string CHITIET { get; set; }
        public Nullable<decimal> GIA_NHAP { get; set; }
        public Nullable<decimal> GIA_BAN { get; set; }
        public Nullable<int> SO_LUONG { get; set; }
        public string HINH_ANH { get; set; }
        public Nullable<System.DateTime> NGAY_NHAP { get; set; }
        public Nullable<double> CAN_NANG { get; set; }
        public Nullable<int> TRANG_THAI { get; set; }
        public Nullable<int> THOI_GIAN_BAO_HANH { get; set; }
        public Nullable<int> MA_NHOM_SP { get; set; }
        public Nullable<int> MA_NCC { get; set; }
        public Nullable<int> SO_LAN_TRUY_CAP { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public string NGUOI_SUA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_HD> CHITIET_HD { get; set; }
        public virtual NHA_CUNG_CAP NHA_CUNG_CAP { get; set; }
        public virtual NHOM_SAN_PHAM NHOM_SAN_PHAM { get; set; }
    }
}
