//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelWebBanHang
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANH_VIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THANH_VIEN()
        {
            this.KHACH_HANG = new HashSet<KHACH_HANG>();
        }
    
        public string MA_TV { get; set; }
        public string MAT_KHAU { get; set; }
        public string TEN_TV { get; set; }
        public Nullable<bool> GIOI_TINH { get; set; }
        public Nullable<System.DateTime> NGAY_SINH { get; set; }
        public string TINH { get; set; }
        public string DIA_CHI { get; set; }
        public string LIEN_HE { get; set; }
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KHACH_HANG> KHACH_HANG { get; set; }
    }
}
