//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelWebBanHang
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class WebBanHang : DbContext
    {
        public WebBanHang()
            : base("name=WebBanHang")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIET_HD> CHITIET_HD { get; set; }
        public virtual DbSet<HOA_DON> HOA_DON { get; set; }
        public virtual DbSet<KHACH_HANG> KHACH_HANG { get; set; }
        public virtual DbSet<NHA_CUNG_CAP> NHA_CUNG_CAP { get; set; }
        public virtual DbSet<NHAN_VIEN> NHAN_VIEN { get; set; }
        public virtual DbSet<NHOM_SAN_PHAM> NHOM_SAN_PHAM { get; set; }
        public virtual DbSet<SAN_PHAM> SAN_PHAM { get; set; }
        public virtual DbSet<THANH_VIEN> THANH_VIEN { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int SP_CHITIET_HD_DELETE(Nullable<int> maSp, Nullable<int> maHd)
        {
            var maSpParameter = maSp.HasValue ?
                new ObjectParameter("MaSp", maSp) :
                new ObjectParameter("MaSp", typeof(int));
    
            var maHdParameter = maHd.HasValue ?
                new ObjectParameter("MaHd", maHd) :
                new ObjectParameter("MaHd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CHITIET_HD_DELETE", maSpParameter, maHdParameter);
        }
    
        public virtual ObjectResult<SP_CHITIET_HD_FIND_Result> SP_CHITIET_HD_FIND(Nullable<bool> searchUsingOR, Nullable<int> maSp, Nullable<int> maHd, Nullable<int> soLuongSp, Nullable<decimal> tongGia)
        {
            var searchUsingORParameter = searchUsingOR.HasValue ?
                new ObjectParameter("SearchUsingOR", searchUsingOR) :
                new ObjectParameter("SearchUsingOR", typeof(bool));
    
            var maSpParameter = maSp.HasValue ?
                new ObjectParameter("MaSp", maSp) :
                new ObjectParameter("MaSp", typeof(int));
    
            var maHdParameter = maHd.HasValue ?
                new ObjectParameter("MaHd", maHd) :
                new ObjectParameter("MaHd", typeof(int));
    
            var soLuongSpParameter = soLuongSp.HasValue ?
                new ObjectParameter("SoLuongSp", soLuongSp) :
                new ObjectParameter("SoLuongSp", typeof(int));
    
            var tongGiaParameter = tongGia.HasValue ?
                new ObjectParameter("TongGia", tongGia) :
                new ObjectParameter("TongGia", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CHITIET_HD_FIND_Result>("SP_CHITIET_HD_FIND", searchUsingORParameter, maSpParameter, maHdParameter, soLuongSpParameter, tongGiaParameter);
        }
    
        public virtual int SP_CHITIET_HD_INSERT(Nullable<int> maSp, Nullable<int> maHd, Nullable<int> soLuongSp, Nullable<decimal> tongGia)
        {
            var maSpParameter = maSp.HasValue ?
                new ObjectParameter("MaSp", maSp) :
                new ObjectParameter("MaSp", typeof(int));
    
            var maHdParameter = maHd.HasValue ?
                new ObjectParameter("MaHd", maHd) :
                new ObjectParameter("MaHd", typeof(int));
    
            var soLuongSpParameter = soLuongSp.HasValue ?
                new ObjectParameter("SoLuongSp", soLuongSp) :
                new ObjectParameter("SoLuongSp", typeof(int));
    
            var tongGiaParameter = tongGia.HasValue ?
                new ObjectParameter("TongGia", tongGia) :
                new ObjectParameter("TongGia", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CHITIET_HD_INSERT", maSpParameter, maHdParameter, soLuongSpParameter, tongGiaParameter);
        }
    
        public virtual ObjectResult<CHITIET_HD> SP_CHITIET_HD_SELECT_ALL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CHITIET_HD>("SP_CHITIET_HD_SELECT_ALL");
        }
    
        public virtual ObjectResult<CHITIET_HD> SP_CHITIET_HD_SELECT_ALL(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CHITIET_HD>("SP_CHITIET_HD_SELECT_ALL", mergeOption);
        }
    
        public virtual ObjectResult<CHITIET_HD> SP_CHITIET_HD_SELECT_By_MaHd(Nullable<int> maHd)
        {
            var maHdParameter = maHd.HasValue ?
                new ObjectParameter("MaHd", maHd) :
                new ObjectParameter("MaHd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CHITIET_HD>("SP_CHITIET_HD_SELECT_By_MaHd", maHdParameter);
        }
    
        public virtual ObjectResult<CHITIET_HD> SP_CHITIET_HD_SELECT_By_MaHd(Nullable<int> maHd, MergeOption mergeOption)
        {
            var maHdParameter = maHd.HasValue ?
                new ObjectParameter("MaHd", maHd) :
                new ObjectParameter("MaHd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CHITIET_HD>("SP_CHITIET_HD_SELECT_By_MaHd", mergeOption, maHdParameter);
        }
    
        public virtual ObjectResult<CHITIET_HD> SP_CHITIET_HD_SELECT_By_MaSp(Nullable<int> maSp)
        {
            var maSpParameter = maSp.HasValue ?
                new ObjectParameter("MaSp", maSp) :
                new ObjectParameter("MaSp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CHITIET_HD>("SP_CHITIET_HD_SELECT_By_MaSp", maSpParameter);
        }
    
        public virtual ObjectResult<CHITIET_HD> SP_CHITIET_HD_SELECT_By_MaSp(Nullable<int> maSp, MergeOption mergeOption)
        {
            var maSpParameter = maSp.HasValue ?
                new ObjectParameter("MaSp", maSp) :
                new ObjectParameter("MaSp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CHITIET_HD>("SP_CHITIET_HD_SELECT_By_MaSp", mergeOption, maSpParameter);
        }
    
        public virtual ObjectResult<CHITIET_HD> SP_CHITIET_HD_SELECT_By_MaSpMaHd(Nullable<int> maSp, Nullable<int> maHd)
        {
            var maSpParameter = maSp.HasValue ?
                new ObjectParameter("MaSp", maSp) :
                new ObjectParameter("MaSp", typeof(int));
    
            var maHdParameter = maHd.HasValue ?
                new ObjectParameter("MaHd", maHd) :
                new ObjectParameter("MaHd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CHITIET_HD>("SP_CHITIET_HD_SELECT_By_MaSpMaHd", maSpParameter, maHdParameter);
        }
    
        public virtual ObjectResult<CHITIET_HD> SP_CHITIET_HD_SELECT_By_MaSpMaHd(Nullable<int> maSp, Nullable<int> maHd, MergeOption mergeOption)
        {
            var maSpParameter = maSp.HasValue ?
                new ObjectParameter("MaSp", maSp) :
                new ObjectParameter("MaSp", typeof(int));
    
            var maHdParameter = maHd.HasValue ?
                new ObjectParameter("MaHd", maHd) :
                new ObjectParameter("MaHd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CHITIET_HD>("SP_CHITIET_HD_SELECT_By_MaSpMaHd", mergeOption, maSpParameter, maHdParameter);
        }
    
        public virtual int SP_CHITIET_HD_SELECT_Paged(string whereClause, string orderBy, Nullable<int> pageIndex, Nullable<int> pageSize)
        {
            var whereClauseParameter = whereClause != null ?
                new ObjectParameter("WhereClause", whereClause) :
                new ObjectParameter("WhereClause", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CHITIET_HD_SELECT_Paged", whereClauseParameter, orderByParameter, pageIndexParameter, pageSizeParameter);
        }
    
        public virtual int SP_CHITIET_HD_UPDATE(Nullable<int> maSp, Nullable<int> originalMaSp, Nullable<int> maHd, Nullable<int> originalMaHd, Nullable<int> soLuongSp, Nullable<decimal> tongGia)
        {
            var maSpParameter = maSp.HasValue ?
                new ObjectParameter("MaSp", maSp) :
                new ObjectParameter("MaSp", typeof(int));
    
            var originalMaSpParameter = originalMaSp.HasValue ?
                new ObjectParameter("OriginalMaSp", originalMaSp) :
                new ObjectParameter("OriginalMaSp", typeof(int));
    
            var maHdParameter = maHd.HasValue ?
                new ObjectParameter("MaHd", maHd) :
                new ObjectParameter("MaHd", typeof(int));
    
            var originalMaHdParameter = originalMaHd.HasValue ?
                new ObjectParameter("OriginalMaHd", originalMaHd) :
                new ObjectParameter("OriginalMaHd", typeof(int));
    
            var soLuongSpParameter = soLuongSp.HasValue ?
                new ObjectParameter("SoLuongSp", soLuongSp) :
                new ObjectParameter("SoLuongSp", typeof(int));
    
            var tongGiaParameter = tongGia.HasValue ?
                new ObjectParameter("TongGia", tongGia) :
                new ObjectParameter("TongGia", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CHITIET_HD_UPDATE", maSpParameter, originalMaSpParameter, maHdParameter, originalMaHdParameter, soLuongSpParameter, tongGiaParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int SP_HOA_DON_DELETE(Nullable<int> maHd)
        {
            var maHdParameter = maHd.HasValue ?
                new ObjectParameter("MaHd", maHd) :
                new ObjectParameter("MaHd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_HOA_DON_DELETE", maHdParameter);
        }
    
        public virtual ObjectResult<SP_HOA_DON_FIND_Result> SP_HOA_DON_FIND(Nullable<bool> searchUsingOR, Nullable<int> maHd, Nullable<int> maKh, string maNv, Nullable<System.DateTime> ngayLap, string tinhGiaoHang, string diaChiGiaoHang, string ghiChu, Nullable<decimal> phiGiaoHang, Nullable<decimal> thanhTien, Nullable<int> trangThai)
        {
            var searchUsingORParameter = searchUsingOR.HasValue ?
                new ObjectParameter("SearchUsingOR", searchUsingOR) :
                new ObjectParameter("SearchUsingOR", typeof(bool));
    
            var maHdParameter = maHd.HasValue ?
                new ObjectParameter("MaHd", maHd) :
                new ObjectParameter("MaHd", typeof(int));
    
            var maKhParameter = maKh.HasValue ?
                new ObjectParameter("MaKh", maKh) :
                new ObjectParameter("MaKh", typeof(int));
    
            var maNvParameter = maNv != null ?
                new ObjectParameter("MaNv", maNv) :
                new ObjectParameter("MaNv", typeof(string));
    
            var ngayLapParameter = ngayLap.HasValue ?
                new ObjectParameter("NgayLap", ngayLap) :
                new ObjectParameter("NgayLap", typeof(System.DateTime));
    
            var tinhGiaoHangParameter = tinhGiaoHang != null ?
                new ObjectParameter("TinhGiaoHang", tinhGiaoHang) :
                new ObjectParameter("TinhGiaoHang", typeof(string));
    
            var diaChiGiaoHangParameter = diaChiGiaoHang != null ?
                new ObjectParameter("DiaChiGiaoHang", diaChiGiaoHang) :
                new ObjectParameter("DiaChiGiaoHang", typeof(string));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            var phiGiaoHangParameter = phiGiaoHang.HasValue ?
                new ObjectParameter("PhiGiaoHang", phiGiaoHang) :
                new ObjectParameter("PhiGiaoHang", typeof(decimal));
    
            var thanhTienParameter = thanhTien.HasValue ?
                new ObjectParameter("ThanhTien", thanhTien) :
                new ObjectParameter("ThanhTien", typeof(decimal));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_HOA_DON_FIND_Result>("SP_HOA_DON_FIND", searchUsingORParameter, maHdParameter, maKhParameter, maNvParameter, ngayLapParameter, tinhGiaoHangParameter, diaChiGiaoHangParameter, ghiChuParameter, phiGiaoHangParameter, thanhTienParameter, trangThaiParameter);
        }
    
        public virtual int SP_HOA_DON_INSERT(ObjectParameter maHd, Nullable<int> maKh, string maNv, Nullable<System.DateTime> ngayLap, string tinhGiaoHang, string diaChiGiaoHang, string ghiChu, Nullable<decimal> phiGiaoHang, Nullable<decimal> thanhTien, Nullable<int> trangThai)
        {
            var maKhParameter = maKh.HasValue ?
                new ObjectParameter("MaKh", maKh) :
                new ObjectParameter("MaKh", typeof(int));
    
            var maNvParameter = maNv != null ?
                new ObjectParameter("MaNv", maNv) :
                new ObjectParameter("MaNv", typeof(string));
    
            var ngayLapParameter = ngayLap.HasValue ?
                new ObjectParameter("NgayLap", ngayLap) :
                new ObjectParameter("NgayLap", typeof(System.DateTime));
    
            var tinhGiaoHangParameter = tinhGiaoHang != null ?
                new ObjectParameter("TinhGiaoHang", tinhGiaoHang) :
                new ObjectParameter("TinhGiaoHang", typeof(string));
    
            var diaChiGiaoHangParameter = diaChiGiaoHang != null ?
                new ObjectParameter("DiaChiGiaoHang", diaChiGiaoHang) :
                new ObjectParameter("DiaChiGiaoHang", typeof(string));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            var phiGiaoHangParameter = phiGiaoHang.HasValue ?
                new ObjectParameter("PhiGiaoHang", phiGiaoHang) :
                new ObjectParameter("PhiGiaoHang", typeof(decimal));
    
            var thanhTienParameter = thanhTien.HasValue ?
                new ObjectParameter("ThanhTien", thanhTien) :
                new ObjectParameter("ThanhTien", typeof(decimal));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_HOA_DON_INSERT", maHd, maKhParameter, maNvParameter, ngayLapParameter, tinhGiaoHangParameter, diaChiGiaoHangParameter, ghiChuParameter, phiGiaoHangParameter, thanhTienParameter, trangThaiParameter);
        }
    
        public virtual ObjectResult<HOA_DON> SP_HOA_DON_SELECT_ALL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HOA_DON>("SP_HOA_DON_SELECT_ALL");
        }
    
        public virtual ObjectResult<HOA_DON> SP_HOA_DON_SELECT_ALL(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HOA_DON>("SP_HOA_DON_SELECT_ALL", mergeOption);
        }
    
        public virtual ObjectResult<HOA_DON> SP_HOA_DON_SELECT_By_MaHd(Nullable<int> maHd)
        {
            var maHdParameter = maHd.HasValue ?
                new ObjectParameter("MaHd", maHd) :
                new ObjectParameter("MaHd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HOA_DON>("SP_HOA_DON_SELECT_By_MaHd", maHdParameter);
        }
    
        public virtual ObjectResult<HOA_DON> SP_HOA_DON_SELECT_By_MaHd(Nullable<int> maHd, MergeOption mergeOption)
        {
            var maHdParameter = maHd.HasValue ?
                new ObjectParameter("MaHd", maHd) :
                new ObjectParameter("MaHd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HOA_DON>("SP_HOA_DON_SELECT_By_MaHd", mergeOption, maHdParameter);
        }
    
        public virtual ObjectResult<HOA_DON> SP_HOA_DON_SELECT_By_MaKh(Nullable<int> maKh)
        {
            var maKhParameter = maKh.HasValue ?
                new ObjectParameter("MaKh", maKh) :
                new ObjectParameter("MaKh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HOA_DON>("SP_HOA_DON_SELECT_By_MaKh", maKhParameter);
        }
    
        public virtual ObjectResult<HOA_DON> SP_HOA_DON_SELECT_By_MaKh(Nullable<int> maKh, MergeOption mergeOption)
        {
            var maKhParameter = maKh.HasValue ?
                new ObjectParameter("MaKh", maKh) :
                new ObjectParameter("MaKh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HOA_DON>("SP_HOA_DON_SELECT_By_MaKh", mergeOption, maKhParameter);
        }
    
        public virtual ObjectResult<HOA_DON> SP_HOA_DON_SELECT_By_MaNv(string maNv)
        {
            var maNvParameter = maNv != null ?
                new ObjectParameter("MaNv", maNv) :
                new ObjectParameter("MaNv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HOA_DON>("SP_HOA_DON_SELECT_By_MaNv", maNvParameter);
        }
    
        public virtual ObjectResult<HOA_DON> SP_HOA_DON_SELECT_By_MaNv(string maNv, MergeOption mergeOption)
        {
            var maNvParameter = maNv != null ?
                new ObjectParameter("MaNv", maNv) :
                new ObjectParameter("MaNv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HOA_DON>("SP_HOA_DON_SELECT_By_MaNv", mergeOption, maNvParameter);
        }
    
        public virtual ObjectResult<HOA_DON> SP_HOA_DON_SELECT_By_MaSpFromChitietHd(Nullable<int> maSp)
        {
            var maSpParameter = maSp.HasValue ?
                new ObjectParameter("MaSp", maSp) :
                new ObjectParameter("MaSp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HOA_DON>("SP_HOA_DON_SELECT_By_MaSpFromChitietHd", maSpParameter);
        }
    
        public virtual ObjectResult<HOA_DON> SP_HOA_DON_SELECT_By_MaSpFromChitietHd(Nullable<int> maSp, MergeOption mergeOption)
        {
            var maSpParameter = maSp.HasValue ?
                new ObjectParameter("MaSp", maSp) :
                new ObjectParameter("MaSp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HOA_DON>("SP_HOA_DON_SELECT_By_MaSpFromChitietHd", mergeOption, maSpParameter);
        }
    
        public virtual int SP_HOA_DON_SELECT_Paged(string whereClause, string orderBy, Nullable<int> pageIndex, Nullable<int> pageSize)
        {
            var whereClauseParameter = whereClause != null ?
                new ObjectParameter("WhereClause", whereClause) :
                new ObjectParameter("WhereClause", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_HOA_DON_SELECT_Paged", whereClauseParameter, orderByParameter, pageIndexParameter, pageSizeParameter);
        }
    
        public virtual int SP_HOA_DON_UPDATE(Nullable<int> maHd, Nullable<int> maKh, string maNv, Nullable<System.DateTime> ngayLap, string tinhGiaoHang, string diaChiGiaoHang, string ghiChu, Nullable<decimal> phiGiaoHang, Nullable<decimal> thanhTien, Nullable<int> trangThai)
        {
            var maHdParameter = maHd.HasValue ?
                new ObjectParameter("MaHd", maHd) :
                new ObjectParameter("MaHd", typeof(int));
    
            var maKhParameter = maKh.HasValue ?
                new ObjectParameter("MaKh", maKh) :
                new ObjectParameter("MaKh", typeof(int));
    
            var maNvParameter = maNv != null ?
                new ObjectParameter("MaNv", maNv) :
                new ObjectParameter("MaNv", typeof(string));
    
            var ngayLapParameter = ngayLap.HasValue ?
                new ObjectParameter("NgayLap", ngayLap) :
                new ObjectParameter("NgayLap", typeof(System.DateTime));
    
            var tinhGiaoHangParameter = tinhGiaoHang != null ?
                new ObjectParameter("TinhGiaoHang", tinhGiaoHang) :
                new ObjectParameter("TinhGiaoHang", typeof(string));
    
            var diaChiGiaoHangParameter = diaChiGiaoHang != null ?
                new ObjectParameter("DiaChiGiaoHang", diaChiGiaoHang) :
                new ObjectParameter("DiaChiGiaoHang", typeof(string));
    
            var ghiChuParameter = ghiChu != null ?
                new ObjectParameter("GhiChu", ghiChu) :
                new ObjectParameter("GhiChu", typeof(string));
    
            var phiGiaoHangParameter = phiGiaoHang.HasValue ?
                new ObjectParameter("PhiGiaoHang", phiGiaoHang) :
                new ObjectParameter("PhiGiaoHang", typeof(decimal));
    
            var thanhTienParameter = thanhTien.HasValue ?
                new ObjectParameter("ThanhTien", thanhTien) :
                new ObjectParameter("ThanhTien", typeof(decimal));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_HOA_DON_UPDATE", maHdParameter, maKhParameter, maNvParameter, ngayLapParameter, tinhGiaoHangParameter, diaChiGiaoHangParameter, ghiChuParameter, phiGiaoHangParameter, thanhTienParameter, trangThaiParameter);
        }
    
        public virtual int SP_KHACH_HANG_DELETE(Nullable<int> maKh)
        {
            var maKhParameter = maKh.HasValue ?
                new ObjectParameter("MaKh", maKh) :
                new ObjectParameter("MaKh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_KHACH_HANG_DELETE", maKhParameter);
        }
    
        public virtual ObjectResult<SP_KHACH_HANG_FIND_Result> SP_KHACH_HANG_FIND(Nullable<bool> searchUsingOR, Nullable<int> maKh, string maTv, string tenKh, Nullable<bool> gioiTinh, Nullable<System.DateTime> ngaySinh, string tinh, string diaChi, string lienHe, string email)
        {
            var searchUsingORParameter = searchUsingOR.HasValue ?
                new ObjectParameter("SearchUsingOR", searchUsingOR) :
                new ObjectParameter("SearchUsingOR", typeof(bool));
    
            var maKhParameter = maKh.HasValue ?
                new ObjectParameter("MaKh", maKh) :
                new ObjectParameter("MaKh", typeof(int));
    
            var maTvParameter = maTv != null ?
                new ObjectParameter("MaTv", maTv) :
                new ObjectParameter("MaTv", typeof(string));
    
            var tenKhParameter = tenKh != null ?
                new ObjectParameter("TenKh", tenKh) :
                new ObjectParameter("TenKh", typeof(string));
    
            var gioiTinhParameter = gioiTinh.HasValue ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(bool));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var tinhParameter = tinh != null ?
                new ObjectParameter("Tinh", tinh) :
                new ObjectParameter("Tinh", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var lienHeParameter = lienHe != null ?
                new ObjectParameter("LienHe", lienHe) :
                new ObjectParameter("LienHe", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_KHACH_HANG_FIND_Result>("SP_KHACH_HANG_FIND", searchUsingORParameter, maKhParameter, maTvParameter, tenKhParameter, gioiTinhParameter, ngaySinhParameter, tinhParameter, diaChiParameter, lienHeParameter, emailParameter);
        }
    
        public virtual int SP_KHACH_HANG_INSERT(ObjectParameter maKh, string maTv, string tenKh, Nullable<bool> gioiTinh, Nullable<System.DateTime> ngaySinh, string tinh, string diaChi, string lienHe, string email)
        {
            var maTvParameter = maTv != null ?
                new ObjectParameter("MaTv", maTv) :
                new ObjectParameter("MaTv", typeof(string));
    
            var tenKhParameter = tenKh != null ?
                new ObjectParameter("TenKh", tenKh) :
                new ObjectParameter("TenKh", typeof(string));
    
            var gioiTinhParameter = gioiTinh.HasValue ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(bool));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var tinhParameter = tinh != null ?
                new ObjectParameter("Tinh", tinh) :
                new ObjectParameter("Tinh", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var lienHeParameter = lienHe != null ?
                new ObjectParameter("LienHe", lienHe) :
                new ObjectParameter("LienHe", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_KHACH_HANG_INSERT", maKh, maTvParameter, tenKhParameter, gioiTinhParameter, ngaySinhParameter, tinhParameter, diaChiParameter, lienHeParameter, emailParameter);
        }
    
        public virtual ObjectResult<KHACH_HANG> SP_KHACH_HANG_SELECT_ALL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KHACH_HANG>("SP_KHACH_HANG_SELECT_ALL");
        }
    
        public virtual ObjectResult<KHACH_HANG> SP_KHACH_HANG_SELECT_ALL(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KHACH_HANG>("SP_KHACH_HANG_SELECT_ALL", mergeOption);
        }
    
        public virtual ObjectResult<KHACH_HANG> SP_KHACH_HANG_SELECT_By_MaKh(Nullable<int> maKh)
        {
            var maKhParameter = maKh.HasValue ?
                new ObjectParameter("MaKh", maKh) :
                new ObjectParameter("MaKh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KHACH_HANG>("SP_KHACH_HANG_SELECT_By_MaKh", maKhParameter);
        }
    
        public virtual ObjectResult<KHACH_HANG> SP_KHACH_HANG_SELECT_By_MaKh(Nullable<int> maKh, MergeOption mergeOption)
        {
            var maKhParameter = maKh.HasValue ?
                new ObjectParameter("MaKh", maKh) :
                new ObjectParameter("MaKh", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KHACH_HANG>("SP_KHACH_HANG_SELECT_By_MaKh", mergeOption, maKhParameter);
        }
    
        public virtual ObjectResult<KHACH_HANG> SP_KHACH_HANG_SELECT_By_MaTv(string maTv)
        {
            var maTvParameter = maTv != null ?
                new ObjectParameter("MaTv", maTv) :
                new ObjectParameter("MaTv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KHACH_HANG>("SP_KHACH_HANG_SELECT_By_MaTv", maTvParameter);
        }
    
        public virtual ObjectResult<KHACH_HANG> SP_KHACH_HANG_SELECT_By_MaTv(string maTv, MergeOption mergeOption)
        {
            var maTvParameter = maTv != null ?
                new ObjectParameter("MaTv", maTv) :
                new ObjectParameter("MaTv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<KHACH_HANG>("SP_KHACH_HANG_SELECT_By_MaTv", mergeOption, maTvParameter);
        }
    
        public virtual int SP_KHACH_HANG_SELECT_Paged(string whereClause, string orderBy, Nullable<int> pageIndex, Nullable<int> pageSize)
        {
            var whereClauseParameter = whereClause != null ?
                new ObjectParameter("WhereClause", whereClause) :
                new ObjectParameter("WhereClause", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_KHACH_HANG_SELECT_Paged", whereClauseParameter, orderByParameter, pageIndexParameter, pageSizeParameter);
        }
    
        public virtual int SP_KHACH_HANG_UPDATE(Nullable<int> maKh, string maTv, string tenKh, Nullable<bool> gioiTinh, Nullable<System.DateTime> ngaySinh, string tinh, string diaChi, string lienHe, string email)
        {
            var maKhParameter = maKh.HasValue ?
                new ObjectParameter("MaKh", maKh) :
                new ObjectParameter("MaKh", typeof(int));
    
            var maTvParameter = maTv != null ?
                new ObjectParameter("MaTv", maTv) :
                new ObjectParameter("MaTv", typeof(string));
    
            var tenKhParameter = tenKh != null ?
                new ObjectParameter("TenKh", tenKh) :
                new ObjectParameter("TenKh", typeof(string));
    
            var gioiTinhParameter = gioiTinh.HasValue ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(bool));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var tinhParameter = tinh != null ?
                new ObjectParameter("Tinh", tinh) :
                new ObjectParameter("Tinh", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var lienHeParameter = lienHe != null ?
                new ObjectParameter("LienHe", lienHe) :
                new ObjectParameter("LienHe", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_KHACH_HANG_UPDATE", maKhParameter, maTvParameter, tenKhParameter, gioiTinhParameter, ngaySinhParameter, tinhParameter, diaChiParameter, lienHeParameter, emailParameter);
        }
    
        public virtual int SP_NHA_CUNG_CAP_DELETE(Nullable<int> maNcc)
        {
            var maNccParameter = maNcc.HasValue ?
                new ObjectParameter("MaNcc", maNcc) :
                new ObjectParameter("MaNcc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_NHA_CUNG_CAP_DELETE", maNccParameter);
        }
    
        public virtual ObjectResult<SP_NHA_CUNG_CAP_FIND_Result> SP_NHA_CUNG_CAP_FIND(Nullable<bool> searchUsingOR, Nullable<int> maNcc, string tenNcc, string quocGia, string diaChi, string lienHe, string email)
        {
            var searchUsingORParameter = searchUsingOR.HasValue ?
                new ObjectParameter("SearchUsingOR", searchUsingOR) :
                new ObjectParameter("SearchUsingOR", typeof(bool));
    
            var maNccParameter = maNcc.HasValue ?
                new ObjectParameter("MaNcc", maNcc) :
                new ObjectParameter("MaNcc", typeof(int));
    
            var tenNccParameter = tenNcc != null ?
                new ObjectParameter("TenNcc", tenNcc) :
                new ObjectParameter("TenNcc", typeof(string));
    
            var quocGiaParameter = quocGia != null ?
                new ObjectParameter("QuocGia", quocGia) :
                new ObjectParameter("QuocGia", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var lienHeParameter = lienHe != null ?
                new ObjectParameter("LienHe", lienHe) :
                new ObjectParameter("LienHe", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_NHA_CUNG_CAP_FIND_Result>("SP_NHA_CUNG_CAP_FIND", searchUsingORParameter, maNccParameter, tenNccParameter, quocGiaParameter, diaChiParameter, lienHeParameter, emailParameter);
        }
    
        public virtual int SP_NHA_CUNG_CAP_INSERT(ObjectParameter maNcc, string tenNcc, string quocGia, string diaChi, string lienHe, string email)
        {
            var tenNccParameter = tenNcc != null ?
                new ObjectParameter("TenNcc", tenNcc) :
                new ObjectParameter("TenNcc", typeof(string));
    
            var quocGiaParameter = quocGia != null ?
                new ObjectParameter("QuocGia", quocGia) :
                new ObjectParameter("QuocGia", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var lienHeParameter = lienHe != null ?
                new ObjectParameter("LienHe", lienHe) :
                new ObjectParameter("LienHe", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_NHA_CUNG_CAP_INSERT", maNcc, tenNccParameter, quocGiaParameter, diaChiParameter, lienHeParameter, emailParameter);
        }
    
        public virtual ObjectResult<NHA_CUNG_CAP> SP_NHA_CUNG_CAP_SELECT_ALL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NHA_CUNG_CAP>("SP_NHA_CUNG_CAP_SELECT_ALL");
        }
    
        public virtual ObjectResult<NHA_CUNG_CAP> SP_NHA_CUNG_CAP_SELECT_ALL(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NHA_CUNG_CAP>("SP_NHA_CUNG_CAP_SELECT_ALL", mergeOption);
        }
    
        public virtual ObjectResult<NHA_CUNG_CAP> SP_NHA_CUNG_CAP_SELECT_By_MaNcc(Nullable<int> maNcc)
        {
            var maNccParameter = maNcc.HasValue ?
                new ObjectParameter("MaNcc", maNcc) :
                new ObjectParameter("MaNcc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NHA_CUNG_CAP>("SP_NHA_CUNG_CAP_SELECT_By_MaNcc", maNccParameter);
        }
    
        public virtual ObjectResult<NHA_CUNG_CAP> SP_NHA_CUNG_CAP_SELECT_By_MaNcc(Nullable<int> maNcc, MergeOption mergeOption)
        {
            var maNccParameter = maNcc.HasValue ?
                new ObjectParameter("MaNcc", maNcc) :
                new ObjectParameter("MaNcc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NHA_CUNG_CAP>("SP_NHA_CUNG_CAP_SELECT_By_MaNcc", mergeOption, maNccParameter);
        }
    
        public virtual int SP_NHA_CUNG_CAP_SELECT_Paged(string whereClause, string orderBy, Nullable<int> pageIndex, Nullable<int> pageSize)
        {
            var whereClauseParameter = whereClause != null ?
                new ObjectParameter("WhereClause", whereClause) :
                new ObjectParameter("WhereClause", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_NHA_CUNG_CAP_SELECT_Paged", whereClauseParameter, orderByParameter, pageIndexParameter, pageSizeParameter);
        }
    
        public virtual int SP_NHA_CUNG_CAP_UPDATE(Nullable<int> maNcc, string tenNcc, string quocGia, string diaChi, string lienHe, string email)
        {
            var maNccParameter = maNcc.HasValue ?
                new ObjectParameter("MaNcc", maNcc) :
                new ObjectParameter("MaNcc", typeof(int));
    
            var tenNccParameter = tenNcc != null ?
                new ObjectParameter("TenNcc", tenNcc) :
                new ObjectParameter("TenNcc", typeof(string));
    
            var quocGiaParameter = quocGia != null ?
                new ObjectParameter("QuocGia", quocGia) :
                new ObjectParameter("QuocGia", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var lienHeParameter = lienHe != null ?
                new ObjectParameter("LienHe", lienHe) :
                new ObjectParameter("LienHe", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_NHA_CUNG_CAP_UPDATE", maNccParameter, tenNccParameter, quocGiaParameter, diaChiParameter, lienHeParameter, emailParameter);
        }
    
        public virtual int SP_NHAN_VIEN_DELETE(string maNv)
        {
            var maNvParameter = maNv != null ?
                new ObjectParameter("MaNv", maNv) :
                new ObjectParameter("MaNv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_NHAN_VIEN_DELETE", maNvParameter);
        }
    
        public virtual ObjectResult<SP_NHAN_VIEN_FIND_Result> SP_NHAN_VIEN_FIND(Nullable<bool> searchUsingOR, string maNv, string matKhau, string tenNv, Nullable<int> chucVu, string lienHe, string email)
        {
            var searchUsingORParameter = searchUsingOR.HasValue ?
                new ObjectParameter("SearchUsingOR", searchUsingOR) :
                new ObjectParameter("SearchUsingOR", typeof(bool));
    
            var maNvParameter = maNv != null ?
                new ObjectParameter("MaNv", maNv) :
                new ObjectParameter("MaNv", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var tenNvParameter = tenNv != null ?
                new ObjectParameter("TenNv", tenNv) :
                new ObjectParameter("TenNv", typeof(string));
    
            var chucVuParameter = chucVu.HasValue ?
                new ObjectParameter("ChucVu", chucVu) :
                new ObjectParameter("ChucVu", typeof(int));
    
            var lienHeParameter = lienHe != null ?
                new ObjectParameter("LienHe", lienHe) :
                new ObjectParameter("LienHe", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_NHAN_VIEN_FIND_Result>("SP_NHAN_VIEN_FIND", searchUsingORParameter, maNvParameter, matKhauParameter, tenNvParameter, chucVuParameter, lienHeParameter, emailParameter);
        }
    
        public virtual int SP_NHAN_VIEN_INSERT(string maNv, string matKhau, string tenNv, Nullable<int> chucVu, string lienHe, string email)
        {
            var maNvParameter = maNv != null ?
                new ObjectParameter("MaNv", maNv) :
                new ObjectParameter("MaNv", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var tenNvParameter = tenNv != null ?
                new ObjectParameter("TenNv", tenNv) :
                new ObjectParameter("TenNv", typeof(string));
    
            var chucVuParameter = chucVu.HasValue ?
                new ObjectParameter("ChucVu", chucVu) :
                new ObjectParameter("ChucVu", typeof(int));
    
            var lienHeParameter = lienHe != null ?
                new ObjectParameter("LienHe", lienHe) :
                new ObjectParameter("LienHe", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_NHAN_VIEN_INSERT", maNvParameter, matKhauParameter, tenNvParameter, chucVuParameter, lienHeParameter, emailParameter);
        }
    
        public virtual ObjectResult<NHAN_VIEN> SP_NHAN_VIEN_SELECT_ALL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NHAN_VIEN>("SP_NHAN_VIEN_SELECT_ALL");
        }
    
        public virtual ObjectResult<NHAN_VIEN> SP_NHAN_VIEN_SELECT_ALL(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NHAN_VIEN>("SP_NHAN_VIEN_SELECT_ALL", mergeOption);
        }
    
        public virtual ObjectResult<NHAN_VIEN> SP_NHAN_VIEN_SELECT_By_MaNv(string maNv)
        {
            var maNvParameter = maNv != null ?
                new ObjectParameter("MaNv", maNv) :
                new ObjectParameter("MaNv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NHAN_VIEN>("SP_NHAN_VIEN_SELECT_By_MaNv", maNvParameter);
        }
    
        public virtual ObjectResult<NHAN_VIEN> SP_NHAN_VIEN_SELECT_By_MaNv(string maNv, MergeOption mergeOption)
        {
            var maNvParameter = maNv != null ?
                new ObjectParameter("MaNv", maNv) :
                new ObjectParameter("MaNv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NHAN_VIEN>("SP_NHAN_VIEN_SELECT_By_MaNv", mergeOption, maNvParameter);
        }
    
        public virtual int SP_NHAN_VIEN_SELECT_Paged(string whereClause, string orderBy, Nullable<int> pageIndex, Nullable<int> pageSize)
        {
            var whereClauseParameter = whereClause != null ?
                new ObjectParameter("WhereClause", whereClause) :
                new ObjectParameter("WhereClause", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_NHAN_VIEN_SELECT_Paged", whereClauseParameter, orderByParameter, pageIndexParameter, pageSizeParameter);
        }
    
        public virtual int SP_NHAN_VIEN_UPDATE(string maNv, string originalMaNv, string matKhau, string tenNv, Nullable<int> chucVu, string lienHe, string email)
        {
            var maNvParameter = maNv != null ?
                new ObjectParameter("MaNv", maNv) :
                new ObjectParameter("MaNv", typeof(string));
    
            var originalMaNvParameter = originalMaNv != null ?
                new ObjectParameter("OriginalMaNv", originalMaNv) :
                new ObjectParameter("OriginalMaNv", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var tenNvParameter = tenNv != null ?
                new ObjectParameter("TenNv", tenNv) :
                new ObjectParameter("TenNv", typeof(string));
    
            var chucVuParameter = chucVu.HasValue ?
                new ObjectParameter("ChucVu", chucVu) :
                new ObjectParameter("ChucVu", typeof(int));
    
            var lienHeParameter = lienHe != null ?
                new ObjectParameter("LienHe", lienHe) :
                new ObjectParameter("LienHe", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_NHAN_VIEN_UPDATE", maNvParameter, originalMaNvParameter, matKhauParameter, tenNvParameter, chucVuParameter, lienHeParameter, emailParameter);
        }
    
        public virtual int SP_NHOM_SAN_PHAM_DELETE(Nullable<int> maNhomSp)
        {
            var maNhomSpParameter = maNhomSp.HasValue ?
                new ObjectParameter("MaNhomSp", maNhomSp) :
                new ObjectParameter("MaNhomSp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_NHOM_SAN_PHAM_DELETE", maNhomSpParameter);
        }
    
        public virtual ObjectResult<SP_NHOM_SAN_PHAM_FIND_Result> SP_NHOM_SAN_PHAM_FIND(Nullable<bool> searchUsingOR, Nullable<int> maNhomSp, string tenNhomSp, Nullable<int> order, Nullable<int> trangThai, Nullable<int> maNhomCha)
        {
            var searchUsingORParameter = searchUsingOR.HasValue ?
                new ObjectParameter("SearchUsingOR", searchUsingOR) :
                new ObjectParameter("SearchUsingOR", typeof(bool));
    
            var maNhomSpParameter = maNhomSp.HasValue ?
                new ObjectParameter("MaNhomSp", maNhomSp) :
                new ObjectParameter("MaNhomSp", typeof(int));
    
            var tenNhomSpParameter = tenNhomSp != null ?
                new ObjectParameter("TenNhomSp", tenNhomSp) :
                new ObjectParameter("TenNhomSp", typeof(string));
    
            var orderParameter = order.HasValue ?
                new ObjectParameter("Order", order) :
                new ObjectParameter("Order", typeof(int));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            var maNhomChaParameter = maNhomCha.HasValue ?
                new ObjectParameter("MaNhomCha", maNhomCha) :
                new ObjectParameter("MaNhomCha", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_NHOM_SAN_PHAM_FIND_Result>("SP_NHOM_SAN_PHAM_FIND", searchUsingORParameter, maNhomSpParameter, tenNhomSpParameter, orderParameter, trangThaiParameter, maNhomChaParameter);
        }
    
        public virtual int SP_NHOM_SAN_PHAM_INSERT(ObjectParameter maNhomSp, string tenNhomSp, Nullable<int> order, Nullable<int> trangThai, Nullable<int> maNhomCha)
        {
            var tenNhomSpParameter = tenNhomSp != null ?
                new ObjectParameter("TenNhomSp", tenNhomSp) :
                new ObjectParameter("TenNhomSp", typeof(string));
    
            var orderParameter = order.HasValue ?
                new ObjectParameter("Order", order) :
                new ObjectParameter("Order", typeof(int));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            var maNhomChaParameter = maNhomCha.HasValue ?
                new ObjectParameter("MaNhomCha", maNhomCha) :
                new ObjectParameter("MaNhomCha", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_NHOM_SAN_PHAM_INSERT", maNhomSp, tenNhomSpParameter, orderParameter, trangThaiParameter, maNhomChaParameter);
        }
    
        public virtual ObjectResult<NHOM_SAN_PHAM> SP_NHOM_SAN_PHAM_SELECT_ALL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NHOM_SAN_PHAM>("SP_NHOM_SAN_PHAM_SELECT_ALL");
        }
    
        public virtual ObjectResult<NHOM_SAN_PHAM> SP_NHOM_SAN_PHAM_SELECT_ALL(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NHOM_SAN_PHAM>("SP_NHOM_SAN_PHAM_SELECT_ALL", mergeOption);
        }
    
        public virtual ObjectResult<NHOM_SAN_PHAM> SP_NHOM_SAN_PHAM_SELECT_By_MaNhomSp(Nullable<int> maNhomSp)
        {
            var maNhomSpParameter = maNhomSp.HasValue ?
                new ObjectParameter("MaNhomSp", maNhomSp) :
                new ObjectParameter("MaNhomSp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NHOM_SAN_PHAM>("SP_NHOM_SAN_PHAM_SELECT_By_MaNhomSp", maNhomSpParameter);
        }
    
        public virtual ObjectResult<NHOM_SAN_PHAM> SP_NHOM_SAN_PHAM_SELECT_By_MaNhomSp(Nullable<int> maNhomSp, MergeOption mergeOption)
        {
            var maNhomSpParameter = maNhomSp.HasValue ?
                new ObjectParameter("MaNhomSp", maNhomSp) :
                new ObjectParameter("MaNhomSp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<NHOM_SAN_PHAM>("SP_NHOM_SAN_PHAM_SELECT_By_MaNhomSp", mergeOption, maNhomSpParameter);
        }
    
        public virtual int SP_NHOM_SAN_PHAM_SELECT_Paged(string whereClause, string orderBy, Nullable<int> pageIndex, Nullable<int> pageSize)
        {
            var whereClauseParameter = whereClause != null ?
                new ObjectParameter("WhereClause", whereClause) :
                new ObjectParameter("WhereClause", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_NHOM_SAN_PHAM_SELECT_Paged", whereClauseParameter, orderByParameter, pageIndexParameter, pageSizeParameter);
        }
    
        public virtual int SP_NHOM_SAN_PHAM_UPDATE(Nullable<int> maNhomSp, string tenNhomSp, Nullable<int> order, Nullable<int> trangThai, Nullable<int> maNhomCha)
        {
            var maNhomSpParameter = maNhomSp.HasValue ?
                new ObjectParameter("MaNhomSp", maNhomSp) :
                new ObjectParameter("MaNhomSp", typeof(int));
    
            var tenNhomSpParameter = tenNhomSp != null ?
                new ObjectParameter("TenNhomSp", tenNhomSp) :
                new ObjectParameter("TenNhomSp", typeof(string));
    
            var orderParameter = order.HasValue ?
                new ObjectParameter("Order", order) :
                new ObjectParameter("Order", typeof(int));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            var maNhomChaParameter = maNhomCha.HasValue ?
                new ObjectParameter("MaNhomCha", maNhomCha) :
                new ObjectParameter("MaNhomCha", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_NHOM_SAN_PHAM_UPDATE", maNhomSpParameter, tenNhomSpParameter, orderParameter, trangThaiParameter, maNhomChaParameter);
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int SP_SAN_PHAM_DELETE(Nullable<int> maSp)
        {
            var maSpParameter = maSp.HasValue ?
                new ObjectParameter("MaSp", maSp) :
                new ObjectParameter("MaSp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SAN_PHAM_DELETE", maSpParameter);
        }
    
        public virtual ObjectResult<SAN_PHAM> SP_SAN_PHAM_FIND(Nullable<bool> searchUsingOR, Nullable<int> maSp, string tenSp, string thongSoKyThuat, string chitiet, Nullable<decimal> giaNhap, Nullable<decimal> giaBan, Nullable<int> soLuong, string hinhAnh, Nullable<System.DateTime> ngayNhap, Nullable<double> canNang, Nullable<int> trangThai, Nullable<int> thoiGianBaoHanh, Nullable<int> maNhomSp, Nullable<int> maNcc)
        {
            var searchUsingORParameter = searchUsingOR.HasValue ?
                new ObjectParameter("SearchUsingOR", searchUsingOR) :
                new ObjectParameter("SearchUsingOR", typeof(bool));
    
            var maSpParameter = maSp.HasValue ?
                new ObjectParameter("MaSp", maSp) :
                new ObjectParameter("MaSp", typeof(int));
    
            var tenSpParameter = tenSp != null ?
                new ObjectParameter("TenSp", tenSp) :
                new ObjectParameter("TenSp", typeof(string));
    
            var thongSoKyThuatParameter = thongSoKyThuat != null ?
                new ObjectParameter("ThongSoKyThuat", thongSoKyThuat) :
                new ObjectParameter("ThongSoKyThuat", typeof(string));
    
            var chitietParameter = chitiet != null ?
                new ObjectParameter("Chitiet", chitiet) :
                new ObjectParameter("Chitiet", typeof(string));
    
            var giaNhapParameter = giaNhap.HasValue ?
                new ObjectParameter("GiaNhap", giaNhap) :
                new ObjectParameter("GiaNhap", typeof(decimal));
    
            var giaBanParameter = giaBan.HasValue ?
                new ObjectParameter("GiaBan", giaBan) :
                new ObjectParameter("GiaBan", typeof(decimal));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var hinhAnhParameter = hinhAnh != null ?
                new ObjectParameter("HinhAnh", hinhAnh) :
                new ObjectParameter("HinhAnh", typeof(string));
    
            var ngayNhapParameter = ngayNhap.HasValue ?
                new ObjectParameter("NgayNhap", ngayNhap) :
                new ObjectParameter("NgayNhap", typeof(System.DateTime));
    
            var canNangParameter = canNang.HasValue ?
                new ObjectParameter("CanNang", canNang) :
                new ObjectParameter("CanNang", typeof(double));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            var thoiGianBaoHanhParameter = thoiGianBaoHanh.HasValue ?
                new ObjectParameter("ThoiGianBaoHanh", thoiGianBaoHanh) :
                new ObjectParameter("ThoiGianBaoHanh", typeof(int));
    
            var maNhomSpParameter = maNhomSp.HasValue ?
                new ObjectParameter("MaNhomSp", maNhomSp) :
                new ObjectParameter("MaNhomSp", typeof(int));
    
            var maNccParameter = maNcc.HasValue ?
                new ObjectParameter("MaNcc", maNcc) :
                new ObjectParameter("MaNcc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SAN_PHAM>("SP_SAN_PHAM_FIND", searchUsingORParameter, maSpParameter, tenSpParameter, thongSoKyThuatParameter, chitietParameter, giaNhapParameter, giaBanParameter, soLuongParameter, hinhAnhParameter, ngayNhapParameter, canNangParameter, trangThaiParameter, thoiGianBaoHanhParameter, maNhomSpParameter, maNccParameter);
        }
    
        public virtual ObjectResult<SAN_PHAM> SP_SAN_PHAM_FIND(Nullable<bool> searchUsingOR, Nullable<int> maSp, string tenSp, string thongSoKyThuat, string chitiet, Nullable<decimal> giaNhap, Nullable<decimal> giaBan, Nullable<int> soLuong, string hinhAnh, Nullable<System.DateTime> ngayNhap, Nullable<double> canNang, Nullable<int> trangThai, Nullable<int> thoiGianBaoHanh, Nullable<int> maNhomSp, Nullable<int> maNcc, MergeOption mergeOption)
        {
            var searchUsingORParameter = searchUsingOR.HasValue ?
                new ObjectParameter("SearchUsingOR", searchUsingOR) :
                new ObjectParameter("SearchUsingOR", typeof(bool));
    
            var maSpParameter = maSp.HasValue ?
                new ObjectParameter("MaSp", maSp) :
                new ObjectParameter("MaSp", typeof(int));
    
            var tenSpParameter = tenSp != null ?
                new ObjectParameter("TenSp", tenSp) :
                new ObjectParameter("TenSp", typeof(string));
    
            var thongSoKyThuatParameter = thongSoKyThuat != null ?
                new ObjectParameter("ThongSoKyThuat", thongSoKyThuat) :
                new ObjectParameter("ThongSoKyThuat", typeof(string));
    
            var chitietParameter = chitiet != null ?
                new ObjectParameter("Chitiet", chitiet) :
                new ObjectParameter("Chitiet", typeof(string));
    
            var giaNhapParameter = giaNhap.HasValue ?
                new ObjectParameter("GiaNhap", giaNhap) :
                new ObjectParameter("GiaNhap", typeof(decimal));
    
            var giaBanParameter = giaBan.HasValue ?
                new ObjectParameter("GiaBan", giaBan) :
                new ObjectParameter("GiaBan", typeof(decimal));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var hinhAnhParameter = hinhAnh != null ?
                new ObjectParameter("HinhAnh", hinhAnh) :
                new ObjectParameter("HinhAnh", typeof(string));
    
            var ngayNhapParameter = ngayNhap.HasValue ?
                new ObjectParameter("NgayNhap", ngayNhap) :
                new ObjectParameter("NgayNhap", typeof(System.DateTime));
    
            var canNangParameter = canNang.HasValue ?
                new ObjectParameter("CanNang", canNang) :
                new ObjectParameter("CanNang", typeof(double));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            var thoiGianBaoHanhParameter = thoiGianBaoHanh.HasValue ?
                new ObjectParameter("ThoiGianBaoHanh", thoiGianBaoHanh) :
                new ObjectParameter("ThoiGianBaoHanh", typeof(int));
    
            var maNhomSpParameter = maNhomSp.HasValue ?
                new ObjectParameter("MaNhomSp", maNhomSp) :
                new ObjectParameter("MaNhomSp", typeof(int));
    
            var maNccParameter = maNcc.HasValue ?
                new ObjectParameter("MaNcc", maNcc) :
                new ObjectParameter("MaNcc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SAN_PHAM>("SP_SAN_PHAM_FIND", mergeOption, searchUsingORParameter, maSpParameter, tenSpParameter, thongSoKyThuatParameter, chitietParameter, giaNhapParameter, giaBanParameter, soLuongParameter, hinhAnhParameter, ngayNhapParameter, canNangParameter, trangThaiParameter, thoiGianBaoHanhParameter, maNhomSpParameter, maNccParameter);
        }
    
        public virtual int SP_SAN_PHAM_INSERT(ObjectParameter maSp, string tenSp, string thongSoKyThuat, string chitiet, Nullable<decimal> giaNhap, Nullable<decimal> giaBan, Nullable<int> soLuong, string hinhAnh, Nullable<System.DateTime> ngayNhap, Nullable<double> canNang, Nullable<int> trangThai, Nullable<int> thoiGianBaoHanh, Nullable<int> maNhomSp, Nullable<int> maNcc)
        {
            var tenSpParameter = tenSp != null ?
                new ObjectParameter("TenSp", tenSp) :
                new ObjectParameter("TenSp", typeof(string));
    
            var thongSoKyThuatParameter = thongSoKyThuat != null ?
                new ObjectParameter("ThongSoKyThuat", thongSoKyThuat) :
                new ObjectParameter("ThongSoKyThuat", typeof(string));
    
            var chitietParameter = chitiet != null ?
                new ObjectParameter("Chitiet", chitiet) :
                new ObjectParameter("Chitiet", typeof(string));
    
            var giaNhapParameter = giaNhap.HasValue ?
                new ObjectParameter("GiaNhap", giaNhap) :
                new ObjectParameter("GiaNhap", typeof(decimal));
    
            var giaBanParameter = giaBan.HasValue ?
                new ObjectParameter("GiaBan", giaBan) :
                new ObjectParameter("GiaBan", typeof(decimal));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var hinhAnhParameter = hinhAnh != null ?
                new ObjectParameter("HinhAnh", hinhAnh) :
                new ObjectParameter("HinhAnh", typeof(string));
    
            var ngayNhapParameter = ngayNhap.HasValue ?
                new ObjectParameter("NgayNhap", ngayNhap) :
                new ObjectParameter("NgayNhap", typeof(System.DateTime));
    
            var canNangParameter = canNang.HasValue ?
                new ObjectParameter("CanNang", canNang) :
                new ObjectParameter("CanNang", typeof(double));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            var thoiGianBaoHanhParameter = thoiGianBaoHanh.HasValue ?
                new ObjectParameter("ThoiGianBaoHanh", thoiGianBaoHanh) :
                new ObjectParameter("ThoiGianBaoHanh", typeof(int));
    
            var maNhomSpParameter = maNhomSp.HasValue ?
                new ObjectParameter("MaNhomSp", maNhomSp) :
                new ObjectParameter("MaNhomSp", typeof(int));
    
            var maNccParameter = maNcc.HasValue ?
                new ObjectParameter("MaNcc", maNcc) :
                new ObjectParameter("MaNcc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SAN_PHAM_INSERT", maSp, tenSpParameter, thongSoKyThuatParameter, chitietParameter, giaNhapParameter, giaBanParameter, soLuongParameter, hinhAnhParameter, ngayNhapParameter, canNangParameter, trangThaiParameter, thoiGianBaoHanhParameter, maNhomSpParameter, maNccParameter);
        }
    
        public virtual ObjectResult<SAN_PHAM> SP_SAN_PHAM_SELECT_ALL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SAN_PHAM>("SP_SAN_PHAM_SELECT_ALL");
        }
    
        public virtual ObjectResult<SAN_PHAM> SP_SAN_PHAM_SELECT_ALL(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SAN_PHAM>("SP_SAN_PHAM_SELECT_ALL", mergeOption);
        }
    
        public virtual ObjectResult<SAN_PHAM> SP_SAN_PHAM_SELECT_By_MaHdFromChitietHd(Nullable<int> maHd)
        {
            var maHdParameter = maHd.HasValue ?
                new ObjectParameter("MaHd", maHd) :
                new ObjectParameter("MaHd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SAN_PHAM>("SP_SAN_PHAM_SELECT_By_MaHdFromChitietHd", maHdParameter);
        }
    
        public virtual ObjectResult<SAN_PHAM> SP_SAN_PHAM_SELECT_By_MaHdFromChitietHd(Nullable<int> maHd, MergeOption mergeOption)
        {
            var maHdParameter = maHd.HasValue ?
                new ObjectParameter("MaHd", maHd) :
                new ObjectParameter("MaHd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SAN_PHAM>("SP_SAN_PHAM_SELECT_By_MaHdFromChitietHd", mergeOption, maHdParameter);
        }
    
        public virtual ObjectResult<SAN_PHAM> SP_SAN_PHAM_SELECT_By_MaNcc(Nullable<int> maNcc)
        {
            var maNccParameter = maNcc.HasValue ?
                new ObjectParameter("MaNcc", maNcc) :
                new ObjectParameter("MaNcc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SAN_PHAM>("SP_SAN_PHAM_SELECT_By_MaNcc", maNccParameter);
        }
    
        public virtual ObjectResult<SAN_PHAM> SP_SAN_PHAM_SELECT_By_MaNcc(Nullable<int> maNcc, MergeOption mergeOption)
        {
            var maNccParameter = maNcc.HasValue ?
                new ObjectParameter("MaNcc", maNcc) :
                new ObjectParameter("MaNcc", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SAN_PHAM>("SP_SAN_PHAM_SELECT_By_MaNcc", mergeOption, maNccParameter);
        }
    
        public virtual ObjectResult<SAN_PHAM> SP_SAN_PHAM_SELECT_By_MaNhomSp(Nullable<int> maNhomSp)
        {
            var maNhomSpParameter = maNhomSp.HasValue ?
                new ObjectParameter("MaNhomSp", maNhomSp) :
                new ObjectParameter("MaNhomSp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SAN_PHAM>("SP_SAN_PHAM_SELECT_By_MaNhomSp", maNhomSpParameter);
        }
    
        public virtual ObjectResult<SAN_PHAM> SP_SAN_PHAM_SELECT_By_MaNhomSp(Nullable<int> maNhomSp, MergeOption mergeOption)
        {
            var maNhomSpParameter = maNhomSp.HasValue ?
                new ObjectParameter("MaNhomSp", maNhomSp) :
                new ObjectParameter("MaNhomSp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SAN_PHAM>("SP_SAN_PHAM_SELECT_By_MaNhomSp", mergeOption, maNhomSpParameter);
        }
    
        public virtual ObjectResult<SAN_PHAM> SP_SAN_PHAM_SELECT_By_MaSp(Nullable<int> maSp)
        {
            var maSpParameter = maSp.HasValue ?
                new ObjectParameter("MaSp", maSp) :
                new ObjectParameter("MaSp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SAN_PHAM>("SP_SAN_PHAM_SELECT_By_MaSp", maSpParameter);
        }
    
        public virtual ObjectResult<SAN_PHAM> SP_SAN_PHAM_SELECT_By_MaSp(Nullable<int> maSp, MergeOption mergeOption)
        {
            var maSpParameter = maSp.HasValue ?
                new ObjectParameter("MaSp", maSp) :
                new ObjectParameter("MaSp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SAN_PHAM>("SP_SAN_PHAM_SELECT_By_MaSp", mergeOption, maSpParameter);
        }
    
        public virtual int SP_SAN_PHAM_SELECT_Paged(string whereClause, string orderBy, Nullable<int> pageIndex, Nullable<int> pageSize)
        {
            var whereClauseParameter = whereClause != null ?
                new ObjectParameter("WhereClause", whereClause) :
                new ObjectParameter("WhereClause", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SAN_PHAM_SELECT_Paged", whereClauseParameter, orderByParameter, pageIndexParameter, pageSizeParameter);
        }
    
        public virtual int SP_SAN_PHAM_UPDATE(Nullable<int> maSp, string tenSp, string thongSoKyThuat, string chitiet, Nullable<decimal> giaNhap, Nullable<decimal> giaBan, Nullable<int> soLuong, string hinhAnh, Nullable<double> canNang, Nullable<int> trangThai, Nullable<int> thoiGianBaoHanh, Nullable<int> maNhomSp, Nullable<int> maNcc, Nullable<System.DateTime> ngaySua, string nguoiSua)
        {
            var maSpParameter = maSp.HasValue ?
                new ObjectParameter("MaSp", maSp) :
                new ObjectParameter("MaSp", typeof(int));
    
            var tenSpParameter = tenSp != null ?
                new ObjectParameter("TenSp", tenSp) :
                new ObjectParameter("TenSp", typeof(string));
    
            var thongSoKyThuatParameter = thongSoKyThuat != null ?
                new ObjectParameter("ThongSoKyThuat", thongSoKyThuat) :
                new ObjectParameter("ThongSoKyThuat", typeof(string));
    
            var chitietParameter = chitiet != null ?
                new ObjectParameter("Chitiet", chitiet) :
                new ObjectParameter("Chitiet", typeof(string));
    
            var giaNhapParameter = giaNhap.HasValue ?
                new ObjectParameter("GiaNhap", giaNhap) :
                new ObjectParameter("GiaNhap", typeof(decimal));
    
            var giaBanParameter = giaBan.HasValue ?
                new ObjectParameter("GiaBan", giaBan) :
                new ObjectParameter("GiaBan", typeof(decimal));
    
            var soLuongParameter = soLuong.HasValue ?
                new ObjectParameter("SoLuong", soLuong) :
                new ObjectParameter("SoLuong", typeof(int));
    
            var hinhAnhParameter = hinhAnh != null ?
                new ObjectParameter("HinhAnh", hinhAnh) :
                new ObjectParameter("HinhAnh", typeof(string));
    
            var canNangParameter = canNang.HasValue ?
                new ObjectParameter("CanNang", canNang) :
                new ObjectParameter("CanNang", typeof(double));
    
            var trangThaiParameter = trangThai.HasValue ?
                new ObjectParameter("TrangThai", trangThai) :
                new ObjectParameter("TrangThai", typeof(int));
    
            var thoiGianBaoHanhParameter = thoiGianBaoHanh.HasValue ?
                new ObjectParameter("ThoiGianBaoHanh", thoiGianBaoHanh) :
                new ObjectParameter("ThoiGianBaoHanh", typeof(int));
    
            var maNhomSpParameter = maNhomSp.HasValue ?
                new ObjectParameter("MaNhomSp", maNhomSp) :
                new ObjectParameter("MaNhomSp", typeof(int));
    
            var maNccParameter = maNcc.HasValue ?
                new ObjectParameter("MaNcc", maNcc) :
                new ObjectParameter("MaNcc", typeof(int));
    
            var ngaySuaParameter = ngaySua.HasValue ?
                new ObjectParameter("NgaySua", ngaySua) :
                new ObjectParameter("NgaySua", typeof(System.DateTime));
    
            var nguoiSuaParameter = nguoiSua != null ?
                new ObjectParameter("NguoiSua", nguoiSua) :
                new ObjectParameter("NguoiSua", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_SAN_PHAM_UPDATE", maSpParameter, tenSpParameter, thongSoKyThuatParameter, chitietParameter, giaNhapParameter, giaBanParameter, soLuongParameter, hinhAnhParameter, canNangParameter, trangThaiParameter, thoiGianBaoHanhParameter, maNhomSpParameter, maNccParameter, ngaySuaParameter, nguoiSuaParameter);
        }
    
        public virtual int SP_THANH_VIEN_DELETE(string maTv)
        {
            var maTvParameter = maTv != null ?
                new ObjectParameter("MaTv", maTv) :
                new ObjectParameter("MaTv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THANH_VIEN_DELETE", maTvParameter);
        }
    
        public virtual ObjectResult<SP_THANH_VIEN_FIND_Result> SP_THANH_VIEN_FIND(Nullable<bool> searchUsingOR, string maTv, string matKhau, string tenTv, Nullable<bool> gioiTinh, Nullable<System.DateTime> ngaySinh, string tinh, string diaChi, string lienHe, string email)
        {
            var searchUsingORParameter = searchUsingOR.HasValue ?
                new ObjectParameter("SearchUsingOR", searchUsingOR) :
                new ObjectParameter("SearchUsingOR", typeof(bool));
    
            var maTvParameter = maTv != null ?
                new ObjectParameter("MaTv", maTv) :
                new ObjectParameter("MaTv", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var tenTvParameter = tenTv != null ?
                new ObjectParameter("TenTv", tenTv) :
                new ObjectParameter("TenTv", typeof(string));
    
            var gioiTinhParameter = gioiTinh.HasValue ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(bool));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var tinhParameter = tinh != null ?
                new ObjectParameter("Tinh", tinh) :
                new ObjectParameter("Tinh", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var lienHeParameter = lienHe != null ?
                new ObjectParameter("LienHe", lienHe) :
                new ObjectParameter("LienHe", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_THANH_VIEN_FIND_Result>("SP_THANH_VIEN_FIND", searchUsingORParameter, maTvParameter, matKhauParameter, tenTvParameter, gioiTinhParameter, ngaySinhParameter, tinhParameter, diaChiParameter, lienHeParameter, emailParameter);
        }
    
        public virtual int SP_THANH_VIEN_INSERT(string maTv, string matKhau, string tenTv, Nullable<bool> gioiTinh, Nullable<System.DateTime> ngaySinh, string tinh, string diaChi, string lienHe, string email)
        {
            var maTvParameter = maTv != null ?
                new ObjectParameter("MaTv", maTv) :
                new ObjectParameter("MaTv", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var tenTvParameter = tenTv != null ?
                new ObjectParameter("TenTv", tenTv) :
                new ObjectParameter("TenTv", typeof(string));
    
            var gioiTinhParameter = gioiTinh.HasValue ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(bool));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var tinhParameter = tinh != null ?
                new ObjectParameter("Tinh", tinh) :
                new ObjectParameter("Tinh", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var lienHeParameter = lienHe != null ?
                new ObjectParameter("LienHe", lienHe) :
                new ObjectParameter("LienHe", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THANH_VIEN_INSERT", maTvParameter, matKhauParameter, tenTvParameter, gioiTinhParameter, ngaySinhParameter, tinhParameter, diaChiParameter, lienHeParameter, emailParameter);
        }
    
        public virtual ObjectResult<THANH_VIEN> SP_THANH_VIEN_SELECT_ALL()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<THANH_VIEN>("SP_THANH_VIEN_SELECT_ALL");
        }
    
        public virtual ObjectResult<THANH_VIEN> SP_THANH_VIEN_SELECT_ALL(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<THANH_VIEN>("SP_THANH_VIEN_SELECT_ALL", mergeOption);
        }
    
        public virtual ObjectResult<THANH_VIEN> SP_THANH_VIEN_SELECT_By_MaTv(string maTv)
        {
            var maTvParameter = maTv != null ?
                new ObjectParameter("MaTv", maTv) :
                new ObjectParameter("MaTv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<THANH_VIEN>("SP_THANH_VIEN_SELECT_By_MaTv", maTvParameter);
        }
    
        public virtual ObjectResult<THANH_VIEN> SP_THANH_VIEN_SELECT_By_MaTv(string maTv, MergeOption mergeOption)
        {
            var maTvParameter = maTv != null ?
                new ObjectParameter("MaTv", maTv) :
                new ObjectParameter("MaTv", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<THANH_VIEN>("SP_THANH_VIEN_SELECT_By_MaTv", mergeOption, maTvParameter);
        }
    
        public virtual int SP_THANH_VIEN_SELECT_Paged(string whereClause, string orderBy, Nullable<int> pageIndex, Nullable<int> pageSize)
        {
            var whereClauseParameter = whereClause != null ?
                new ObjectParameter("WhereClause", whereClause) :
                new ObjectParameter("WhereClause", typeof(string));
    
            var orderByParameter = orderBy != null ?
                new ObjectParameter("OrderBy", orderBy) :
                new ObjectParameter("OrderBy", typeof(string));
    
            var pageIndexParameter = pageIndex.HasValue ?
                new ObjectParameter("PageIndex", pageIndex) :
                new ObjectParameter("PageIndex", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THANH_VIEN_SELECT_Paged", whereClauseParameter, orderByParameter, pageIndexParameter, pageSizeParameter);
        }
    
        public virtual int SP_THANH_VIEN_UPDATE(string maTv, string originalMaTv, string matKhau, string tenTv, Nullable<bool> gioiTinh, Nullable<System.DateTime> ngaySinh, string tinh, string diaChi, string lienHe, string email)
        {
            var maTvParameter = maTv != null ?
                new ObjectParameter("MaTv", maTv) :
                new ObjectParameter("MaTv", typeof(string));
    
            var originalMaTvParameter = originalMaTv != null ?
                new ObjectParameter("OriginalMaTv", originalMaTv) :
                new ObjectParameter("OriginalMaTv", typeof(string));
    
            var matKhauParameter = matKhau != null ?
                new ObjectParameter("MatKhau", matKhau) :
                new ObjectParameter("MatKhau", typeof(string));
    
            var tenTvParameter = tenTv != null ?
                new ObjectParameter("TenTv", tenTv) :
                new ObjectParameter("TenTv", typeof(string));
    
            var gioiTinhParameter = gioiTinh.HasValue ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(bool));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var tinhParameter = tinh != null ?
                new ObjectParameter("Tinh", tinh) :
                new ObjectParameter("Tinh", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var lienHeParameter = lienHe != null ?
                new ObjectParameter("LienHe", lienHe) :
                new ObjectParameter("LienHe", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THANH_VIEN_UPDATE", maTvParameter, originalMaTvParameter, matKhauParameter, tenTvParameter, gioiTinhParameter, ngaySinhParameter, tinhParameter, diaChiParameter, lienHeParameter, emailParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<SAN_PHAM> SP_SAN_PHAM_SELECT_By_MaNhomSp_BaoGom_MaNhomCha(Nullable<int> maNhomSp)
        {
            var maNhomSpParameter = maNhomSp.HasValue ?
                new ObjectParameter("MaNhomSp", maNhomSp) :
                new ObjectParameter("MaNhomSp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SAN_PHAM>("SP_SAN_PHAM_SELECT_By_MaNhomSp_BaoGom_MaNhomCha", maNhomSpParameter);
        }
    
        public virtual ObjectResult<SAN_PHAM> SP_SAN_PHAM_SELECT_By_MaNhomSp_BaoGom_MaNhomCha(Nullable<int> maNhomSp, MergeOption mergeOption)
        {
            var maNhomSpParameter = maNhomSp.HasValue ?
                new ObjectParameter("MaNhomSp", maNhomSp) :
                new ObjectParameter("MaNhomSp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SAN_PHAM>("SP_SAN_PHAM_SELECT_By_MaNhomSp_BaoGom_MaNhomCha", mergeOption, maNhomSpParameter);
        }
    }
}
